module.exports = {
  semi: false,
  endOfLine: 'auto',
  trailingComma: 'es5',
  arrowParens: 'always',
  quoteProps: 'as-needed',
  bracketSameLine: false,
  jsxSingleQuote: false,
  bracketSpacing: true,
  singleQuote: true,
  printWidth: 100,
  useTabs: false,
  tabWidth: 2,

  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^@(server|trpc)/(.*)$',
    '<THIRD_PARTY_MODULES>',
    '^@/(configs|libs)(.*)$',
    '^@/(redux|router)(.*)$',
    '^@/(constants|hooks|assets)(.*)$',
    '^@/(components)(.*)$',
    '^@/(layouts|contexts)(.*)$',
    '^@/(pages|views|containers)(.*)$',
    '^@/(utils/helper)(.*)$',
    '^@/(utils/validators)(.*)$',
    '^@/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],

  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
}
